name: My First Workflow
on: 
  push:
  schedule:
    - cron: '*/15 * * *' # Runs every day at midnight
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!" 
  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, World!"
