name: CLone repository
on: push


jobs:
    test:
      runs-on: ubuntu-latest


      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '18'
        - name: version check
          run: node -v
        
